// Custom player priority order for display
// Players not in this list will appear at the end in their original order

export const PLAYER_PRIORITY_ORDER: string[] = [
  "Jasprit Bumrah",
  "Sunil Narine",
  "Sanju Samson",
  "Yashasvi Jaiswal",
  "Virat Kohli",
  "KL Rahul",
  "Shubman Gill",
  "Rishabh Pant",
  "Shreyas Iyer",
  "Abhishek Sharma",
  "Suryakumar Yadav",
  "Cameron Green",
  "Ruturaj Gaikwad",
  "Ravindra Jadeja",
  "Phil Salt",
  "Axar Patel",
  "Sai Sudharsan",
  "Nicholas Pooran",
  "Yuzvendra Chahal",
  "Travis Head",
  "Hardik Pandya",
  "Varun Chakravarthy",
  "Noor Ahmad",
  "Vaibhav Suryavanshi",
  "Rajat Patidar",
  "Kuldeep Yadav",
  "Jos Buttler",
  "Mitchell Marsh",
  "Arshdeep Singh",
  "Ishan Kishan",
  "Tilak Varma",
  "Ajinkya Rahane",
  "Shivam Dube",
  "Riyan Parag",
  "Josh Hazlewood",
  "Mitchell Starc",
  "Rashid Khan",
  "Aiden Markram",
  "Priyansh Arya",
  "Heinrich Klaasen",
  "Rohit Sharma",
  "Harshit Rana",
  "Dewald Brevis",
  "Jofra Archer",
  "Bhuvneshwar Kumar",
  "Tristan Stubbs",
  "Mohammed Siraj",
  "Mohammed Shami",
  "Marco Jansen",
  "Pat Cummins",
  "Trent Boult",
  "Matheesha Pathirana",
  "Ayush Mhatre",
  "Dhruv Jurel",
  "Venkatesh Iyer",
  "Nitish Rana",
  "Prasidh Krishna",
  "Ayush Badoni",
  "Prabhsimran Singh",
  "Harshal Patel",
  "Mitchell Santner",
  "Rinku Singh",
  "Khaleel Ahmed",
  "Ravi Bishnoi",
  "Krunal Pandya",
  "Ashutosh Sharma",
  "Kagiso Rabada",
  "Avesh Khan",
  "Marcus Stoinis",
  "Nitish Kumar Reddy",
  "Naman Dhir",
  "Ramandeep Singh",
  "Anshul Kamboj",
  "Shimron Hetmyer",
  "Devdutt Padikkal",
  "Vipraj Nigam",
  "Sai Kishore",
  "Digvesh Singh Rathi",
  "Shashank Singh",
  "Liam Livingstone",
  "Ryan Rickelton",
  "Mustafizur Rahman",
  "Prasanth Veer",
  "Sandeep Sharma",
  "Jitesh Sharma",
  "David Miller",
  "Washington Sundar",
  "Abdul Samad",
  "Lockie Ferguson",
  "Aniket Varma",
  "Deepak Chahar",
  "Rahul Tripathi",
  "Kartik Sharma",
  "Sam Curran",
  "Yash Dayal",
  "T Natarajan",
  "Shahbaz Ahmed",
  "Mitch Owen",
  "Jaydev Unadkat",
  "Will Jacks",
  "Angkrish Raghuvanshi",
  "Urvil Patel",
  "Tushar Deshpande",
  "Suyash Sharma",
  "Prithvi Shaw",
  "Glenn Phillips",
  "Wanindu Hasaranga",
  "Nehal Wadhera",
  "Harsh Dubey",
  "Quinton de Kock",
  "Vaibhav Arora",
  "Nathan Ellis",
  "Shubham Dubey",
  "Rasikh Dar",
  "Abishek Porel",
  "Rahul Tewatia",
  "Anrich Nortje",
  "Harpreet Brar",
  "Smaran Ravichandran",
  "Shardul Thakur",
  "Akash Deep",
  "MS Dhoni",
  "Vignesh Puthur",
  "Tim David",
  "Auqib Nabi Dar",
  "Jason Holder",
  "Mayank Yadav",
  "Azmatullah Omarzai",
  "Salil Arora",
  "Sherfane Rutherford",
  "Rachin Ravindra",
  "Rahul Chahar",
  "Aman Rao Perala",
  "Romario Shepherd",
  "Sameer Rizvi",
  "Ishant Sharma",
  "Mohsin Khan",
  "Yash Thakur",
  "Zeeshan Ansari",
  "Corbin Bosch",
  "Tim Seifert",
  "Matt Henry",
  "Lhuan-Dre Pretorious",
  "Jacob Bethell",
  "Karun Nair",
  "Arshad Khan",
  "Matthew Breetzke",
  "Vyshak Vijaykumar",
  "Shivam Mavi",
  "Ashwani Kumar",
  "Rovman Powell",
  "Sarfaraz Khan",
  "Donovan Ferreira",
  "Jacob Duffy",
  "Pathum Nissanka",
  "Ashok Sharma",
  "Mukul Choudhary",
  "Vishnu Vinod",
  "Echan Malinga",
  "Mayank Markande",
  "Umran Malik",
  "Akeal Hosein",
  "Nandre Burger",
  "Nuwan Thushara",
  "Kyle Jamieson",
  "Manav Suthar",
  "Akash Singh",
  "Xavier Bartlett",
  "Brydon Carse",
  "Robin Minz",
  "Finn Allen",
  "Jamie Overton",
  "Kuldeep Sen",
  "Mangesh Yadav",
  "Dushmantha Chameera",
  "Shahrukh Khan",
  "Arjun Tendulkar",
  "Cooper Connolly",
  "Mukesh Kumar",
  "Shivang Kumar",
  "Allah Ghazanfar",
  "Kartik Tyagi",
  "Mathew Short",
  "Adam Milne",
  "Swapnil Singh",
  "Kumar Kushagra",
  "Naman Tiwari",
  "Pyla Avinash",
  "Kamindu Mendis",
  "Raj Angad Bawa",
  "Prashant Solanki",
  "Ramakrishna Ghosh",
  "Kwena Maphaka",
  "Abhinandan Singh",
  "Lungi Ngidi",
  "Nishant Sindhu",
  "Himmat Singh",
  "Harnoor Pannu",
  "Sakib Hussain",
  "Raghu Sharma",
  "Manish Pandey",
  "Gurjapneet Singh",
  "Yudhvir Singh",
  "Satvik Deswal",
  "Ben Duckett",
  "Gurnoor Brar",
  "Arshin Kulkarni",
  "Suryansh Shedge",
  "Onkar Tarmale",
  "Danish Malewar",
  "Anukul Roy",
  "Mukesh Choudhary",
  "Sushant Mishra",
  "Jordan Cox",
  "Ajay Mandal",
  "Jayant Yadav",
  "M Siddharth",
  "Ben Dwarshuis",
  "Amit Kumar",
  "Mohammed Izhar",
  "Daksh Kamra",
  "Shreyas Gopal",
  "Yash Raj Punja",
  "Vicky Ostwal",
  "Madhav Tiwari",
  "Anuj Rawat",
  "Prince Yadav",
  "Musheer Khan",
  "Praful Hinge",
  "Mayank Rawat",
  "Sarthak Ranjan",
  "Aman Khan",
  "Ravi Singh",
  "Vihaan Malhotra",
  "Tripurana Vijay",
  "Tom Banton",
  "Akshat Raghuwanshi",
  "Vishal Nishad",
  "Krains Fuletra",
  "Atharva Ankolekar",
  "Tejasvi Dahiya",
  "Zakary Foulkes",
  "Brijesh Sharma",
  "Kanishk Chouhan",
  "Sahil Parekh",
  "Prithvi Raj Yarra",
  "Josh Inglis",
  "Praveen Dubey",
  "Jack Edwards",
];

// Create a lookup map for O(1) access
const playerPriorityMap = new Map<string, number>();
PLAYER_PRIORITY_ORDER.forEach((name, index) => {
  playerPriorityMap.set(name.toLowerCase(), index);
});

/**
 * Get the priority index for a player name.
 * Returns a very high number for players not in the priority list.
 */
export function getPlayerPriority(playerName: string): number {
  const priority = playerPriorityMap.get(playerName.toLowerCase());
  return priority !== undefined ? priority : Number.MAX_SAFE_INTEGER;
}

/**
 * Sort players by the custom priority order.
 * Players not in the list appear at the end in their original order.
 */
export function sortPlayersByPriority<T extends { name: string }>(players: T[]): T[] {
  return [...players].sort((a, b) => {
    const priorityA = getPlayerPriority(a.name);
    const priorityB = getPlayerPriority(b.name);
    return priorityA - priorityB;
  });
}
