import fs from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const rawData = fs.readFileSync(path.join(__dirname, 't20_schedule.json'), 'utf-8');
const data = JSON.parse(rawData);

let sql = `-- Seed T20 WC 2026 Schedule
-- Generated by scripts/generate_schedule_migration.js

-- Clear existing matches for this series to avoid duplicates if re-run
DELETE FROM cricket_matches WHERE series_id = 11253;

`;

function cleanString(str) {
    if (!str) return 'NULL';
    return `'${str.replace(/'/g, "''")}'`;
}

if (data.matchDetails) {
    data.matchDetails.forEach(detail => {
        if (detail.matchDetailsMap && detail.matchDetailsMap.match) {
            detail.matchDetailsMap.match.forEach(match => {
                const info = match.matchInfo;

                // Only process if it has required fields
                if (!info || !info.matchId) return;

                const date = new Date(parseInt(info.startDate));
                const isoDate = date.toISOString();

                const matchId = info.matchId;
                const seriesId = info.seriesId;
                const matchDesc = cleanString(info.matchDesc);
                const matchFormat = cleanString(info.matchFormat);
                const state = cleanString(info.state);

                // Use result status if available, otherwise just use status text
                const result = cleanString(info.status);

                const team1Id = info.team1?.teamId || 'NULL';
                const team1Name = cleanString(info.team1?.teamName);
                const team1Short = cleanString(info.team1?.teamSName);

                const team2Id = info.team2?.teamId || 'NULL';
                const team2Name = cleanString(info.team2?.teamName);
                const team2Short = cleanString(info.team2?.teamSName);

                const venue = cleanString(info.venueInfo?.ground);
                const city = cleanString(info.venueInfo?.city);

                sql += `INSERT INTO cricket_matches (
    cricbuzz_match_id, 
    series_id, 
    match_description, 
    match_format, 
    match_date, 
    state, 
    result, 
    team1_id, 
    team1_name, 
    team1_short, 
    team2_id, 
    team2_name, 
    team2_short, 
    venue, 
    city
) VALUES (
    ${matchId}, 
    ${seriesId}, 
    ${matchDesc}, 
    ${matchFormat}, 
    '${isoDate}', 
    ${state}, 
    ${result}, 
    ${team1Id}, 
    ${team1Name}, 
    ${team1Short}, 
    ${team2Id}, 
    ${team2Name}, 
    ${team2Short}, 
    ${venue}, 
    ${city}
);\n`;
            });
        }
    });
}

console.log(sql);
