import { useState, useEffect } from 'react';
import { Loader2, Wand2, Check } from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui/dialog';
import { toast } from 'sonner';
import { supabase } from '@/integrations/supabase/client';

interface ProposedAssignment {
  match_id: string;
  match_title: string;
  match_date: string;
  proposed_week: number;
}

interface AutoGenerateDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  leagueId: string;
  onApplied: () => void;
}

export const AutoGenerateDialog = ({
  open,
  onOpenChange,
  leagueId,
  onApplied,
}: AutoGenerateDialogProps) => {
  const [proposals, setProposals] = useState<ProposedAssignment[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [isApplying, setIsApplying] = useState(false);

  // Fetch preview when dialog opens
  useEffect(() => {
    if (!open || !leagueId) return;

    const fetchPreview = async () => {
      setIsLoading(true);
      try {
        const { data, error } = await supabase.rpc('auto_generate_weeks', {
          p_league_id: leagueId,
          p_interval_days: 7,
        });

        if (error) {
          toast.error(`Failed to generate preview: ${error.message}`);
          return;
        }

        setProposals((data as ProposedAssignment[]) || []);
      } catch {
        toast.error('Failed to generate week preview');
      } finally {
        setIsLoading(false);
      }
    };

    fetchPreview();
  }, [open, leagueId]);

  const handleApply = async () => {
    if (proposals.length === 0) return;

    setIsApplying(true);
    try {
      const assignments = proposals.map((p) => ({
        match_id: p.match_id,
        week: p.proposed_week,
      }));

      const { error } = await supabase.rpc('bulk_update_match_weeks', {
        p_league_id: leagueId,
        p_assignments: assignments,
      });

      if (error) {
        toast.error(`Failed to apply: ${error.message}`);
        return;
      }

      toast.success(`Assigned ${proposals.length} matches across weeks`);
      onOpenChange(false);
      onApplied();
    } catch {
      toast.error('Failed to apply week assignments');
    } finally {
      setIsApplying(false);
    }
  };

  // Group proposals by week for display
  const groupedByWeek = proposals.reduce<Record<number, ProposedAssignment[]>>((acc, p) => {
    if (!acc[p.proposed_week]) acc[p.proposed_week] = [];
    acc[p.proposed_week].push(p);
    return acc;
  }, {});

  const weekNumbers = Object.keys(groupedByWeek)
    .map(Number)
    .sort((a, b) => a - b);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-lg">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Wand2 className="w-4 h-4" />
            Auto-Generate Weeks
          </DialogTitle>
        </DialogHeader>

        {isLoading ? (
          <div className="flex items-center justify-center py-8">
            <Loader2 className="w-6 h-6 animate-spin text-muted-foreground" />
          </div>
        ) : proposals.length === 0 ? (
          <p className="text-sm text-muted-foreground text-center py-6">
            No unassigned matches to group into weeks.
          </p>
        ) : (
          <div className="space-y-4 max-h-[400px] overflow-y-auto">
            <p className="text-xs text-muted-foreground">
              Matches grouped into 7-day windows. Review and apply:
            </p>
            {weekNumbers.map((weekNum) => (
              <div key={weekNum} className="border rounded-lg p-3 space-y-1">
                <p className="text-sm font-medium">
                  Week {weekNum}
                  <span className="text-xs text-muted-foreground ml-2">
                    ({groupedByWeek[weekNum].length} matches)
                  </span>
                </p>
                {groupedByWeek[weekNum].map((p) => (
                  <div key={p.match_id} className="text-xs text-muted-foreground flex justify-between">
                    <span className="truncate">{p.match_title}</span>
                    <span className="whitespace-nowrap ml-2">
                      {new Date(p.match_date).toLocaleDateString('en-US', {
                        month: 'short',
                        day: 'numeric',
                      })}
                    </span>
                  </div>
                ))}
              </div>
            ))}
          </div>
        )}

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)} disabled={isApplying}>
            Cancel
          </Button>
          <Button onClick={handleApply} disabled={isApplying || proposals.length === 0}>
            {isApplying ? (
              <>
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                Applying...
              </>
            ) : (
              <>
                <Check className="w-4 h-4 mr-2" />
                Apply ({proposals.length} matches)
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};
