import { useState, useEffect, useCallback } from 'react';
import { Wand2, Plus, Loader2, Check, AlertCircle } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui/dialog';
import { supabase } from '@/integrations/supabase/client';
import { WeekCard } from './WeekCard';
import { MatchAssignDialog } from './MatchAssignDialog';
import { AutoGenerateDialog } from './AutoGenerateDialog';

interface MatchInfo {
  match_id: string;
  match_title: string;
  match_date: string;
  state: string;
  stats_imported: boolean;
  week: number | null;
}

interface WeekReadiness {
  total_matches: number;
  finalized_matches: number;
  is_ready: boolean;
}

interface WeekGroup {
  week: number | null;
  matches: MatchInfo[];
  readiness?: WeekReadiness;
  isFinalized: boolean;
}

interface WeekManagerProps {
  leagueId: string;
}

export const WeekManager = ({ leagueId }: WeekManagerProps) => {
  const [weekGroups, setWeekGroups] = useState<WeekGroup[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [isFinalizing, setIsFinalizing] = useState(false);
  const [confirmFinalizeWeek, setConfirmFinalizeWeek] = useState<number | null>(null);

  // Dialog state
  const [assignDialogWeek, setAssignDialogWeek] = useState<number | null>(null);
  const [autoGenerateOpen, setAutoGenerateOpen] = useState(false);

  const fetchData = useCallback(async () => {
    if (!leagueId) return;
    setIsLoading(true);

    try {
      // Fetch all league_matches with joined cricket_match data
      const { data: matchesData, error: matchesError } = await supabase
        .from('league_matches')
        .select(`
          match_id,
          week,
          stats_imported,
          cricket_matches!inner (
            match_description,
            match_date,
            state,
            team1_name,
            team2_name
          )
        `)
        .eq('league_id', leagueId)
        .order('week');

      if (matchesError) throw matchesError;

      // Transform into MatchInfo array
      const allMatches: MatchInfo[] = (matchesData || []).map((row) => {
        const cm = row.cricket_matches;
        return {
          match_id: row.match_id,
          week: row.week,
          stats_imported: row.stats_imported || false,
          match_title:
            cm.match_description ||
            `${cm.team1_name || 'TBC'} vs ${cm.team2_name || 'TBC'}`,
          match_date: cm.match_date || '',
          state: cm.state || 'Upcoming',
        };
      });

      // Group by week
      const weekMap = new Map<number | null, MatchInfo[]>();
      for (const match of allMatches) {
        const key = match.week;
        if (!weekMap.has(key)) weekMap.set(key, []);
        weekMap.get(key)!.push(match);
      }

      // Sort matches within each group by date
      for (const matches of weekMap.values()) {
        matches.sort((a, b) => new Date(a.match_date).getTime() - new Date(b.match_date).getTime());
      }

      // Get distinct non-null weeks for readiness checks
      const weekNumbers = [...weekMap.keys()].filter((w): w is number => w !== null).sort((a, b) => a - b);

      // Check readiness and finalization for each week
      const readinessResults = await Promise.all(
        weekNumbers.map(async (week) => {
          const [readinessResult, matchupsResult] = await Promise.all([
            supabase.rpc('check_week_finalization_ready', {
              p_league_id: leagueId,
              p_week: week,
            }),
            supabase
              .from('league_matchups')
              .select('is_finalized')
              .eq('league_id', leagueId)
              .eq('week', week),
          ]);

          const readiness = readinessResult.data?.[0] as WeekReadiness | undefined;
          const matchups = matchupsResult.data || [];
          const isFinalized = matchups.length > 0 && matchups.every((m) => m.is_finalized);

          return { week, readiness, isFinalized };
        })
      );

      const readinessMap = new Map(readinessResults.map((r) => [r.week, r]));

      // Build week groups: numbered weeks first, then unassigned
      const groups: WeekGroup[] = [];

      for (const week of weekNumbers) {
        const r = readinessMap.get(week);
        groups.push({
          week,
          matches: weekMap.get(week) || [],
          readiness: r?.readiness,
          isFinalized: r?.isFinalized || false,
        });
      }

      // Add unassigned group if there are unassigned matches
      const unassigned = weekMap.get(null);
      if (unassigned && unassigned.length > 0) {
        groups.push({
          week: null,
          matches: unassigned,
          isFinalized: false,
        });
      }

      setWeekGroups(groups);
    } catch (error) {
      console.error('Error fetching week data:', error);
      toast.error('Failed to load week data');
    } finally {
      setIsLoading(false);
    }
  }, [leagueId]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  const handleFinalizeWeek = async () => {
    if (confirmFinalizeWeek === null) return;

    setIsFinalizing(true);
    try {
      const { error } = await supabase.rpc('finalize_week', {
        p_league_id: leagueId,
        p_week: confirmFinalizeWeek,
      });

      if (error) {
        toast.error(`Failed to finalize week: ${error.message}`);
        return;
      }

      toast.success(`Week ${confirmFinalizeWeek} finalized successfully`);
      setConfirmFinalizeWeek(null);
      await fetchData();
    } catch {
      toast.error('Failed to finalize week');
    } finally {
      setIsFinalizing(false);
    }
  };

  const handleAddNewWeek = async () => {
    // Find the next week number
    const existingWeeks = weekGroups
      .map((g) => g.week)
      .filter((w): w is number => w !== null);
    const nextWeek = existingWeeks.length > 0 ? Math.max(...existingWeeks) + 1 : 1;

    // Open the assign dialog directly for the new week number
    setAssignDialogWeek(nextWeek);
  };

  // Collect unassigned matches for the assign dialog
  const unassignedMatches = weekGroups
    .find((g) => g.week === null)
    ?.matches.map((m) => ({
      match_id: m.match_id,
      match_title: m.match_title,
      match_date: m.match_date,
    })) || [];

  const hasUnassigned = unassignedMatches.length > 0;

  return (
    <div className="space-y-4">
      {/* Action Bar */}
      <div className="flex items-center gap-2">
        {hasUnassigned && (
          <Button
            variant="outline"
            size="sm"
            className="h-8 text-xs"
            onClick={() => setAutoGenerateOpen(true)}
          >
            <Wand2 className="w-3 h-3 mr-1" />
            Auto-Generate Weeks
          </Button>
        )}
        <Button
          variant="outline"
          size="sm"
          className="h-8 text-xs"
          onClick={handleAddNewWeek}
          disabled={!hasUnassigned}
        >
          <Plus className="w-3 h-3 mr-1" />
          New Week
        </Button>
      </div>

      {/* Week Cards */}
      {isLoading ? (
        <div className="flex items-center justify-center py-8">
          <Loader2 className="w-6 h-6 animate-spin text-muted-foreground" />
        </div>
      ) : weekGroups.length === 0 ? (
        <p className="text-sm text-muted-foreground text-center py-4">
          No matches found for this league.
        </p>
      ) : (
        <div className="space-y-2">
          {weekGroups.map((group) => (
            <WeekCard
              key={group.week ?? 'unassigned'}
              leagueId={leagueId}
              week={group.week}
              matches={group.matches}
              readiness={group.readiness}
              isFinalized={group.isFinalized}
              onMatchRemoved={fetchData}
              onAddMatchesClick={(week) => setAssignDialogWeek(week)}
              onFinalizeClick={(week) => setConfirmFinalizeWeek(week)}
            />
          ))}
        </div>
      )}

      {/* Assign Matches Dialog */}
      {assignDialogWeek !== null && (
        <MatchAssignDialog
          open={true}
          onOpenChange={(open) => {
            if (!open) setAssignDialogWeek(null);
          }}
          leagueId={leagueId}
          targetWeek={assignDialogWeek}
          unassignedMatches={unassignedMatches}
          onAssigned={fetchData}
        />
      )}

      {/* Auto-Generate Dialog */}
      <AutoGenerateDialog
        open={autoGenerateOpen}
        onOpenChange={setAutoGenerateOpen}
        leagueId={leagueId}
        onApplied={fetchData}
      />

      {/* Finalize Confirmation Dialog */}
      <Dialog
        open={confirmFinalizeWeek !== null}
        onOpenChange={(open) => {
          if (!open) setConfirmFinalizeWeek(null);
        }}
      >
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Finalize Week {confirmFinalizeWeek}</DialogTitle>
          </DialogHeader>
          <div className="space-y-3">
            <p className="text-sm text-muted-foreground">
              This will calculate final scores with C/VC multipliers, determine matchup winners,
              and update W/L standings.
            </p>
            <p className="text-sm text-yellow-600 flex items-center gap-2">
              <AlertCircle className="w-4 h-4" />
              This action cannot be undone.
            </p>
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setConfirmFinalizeWeek(null)}
              disabled={isFinalizing}
            >
              Cancel
            </Button>
            <Button onClick={handleFinalizeWeek} disabled={isFinalizing}>
              {isFinalizing ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Finalizing...
                </>
              ) : (
                <>
                  <Check className="w-4 h-4 mr-2" />
                  Confirm Finalize
                </>
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
};
