import { useState, useEffect, useCallback } from 'react';
import { Wand2, Plus, Loader2 } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { supabase } from '@/integrations/supabase/client';
import { WeekCard } from './WeekCard';
import { MatchAssignDialog } from './MatchAssignDialog';
import { AutoGenerateDialog } from './AutoGenerateDialog';

interface MatchInfo {
  match_id: string;
  match_title: string;
  match_date: string;
  state: string;
  stats_imported: boolean;
  week: number | null;
}

interface WeekGroup {
  week: number | null;
  matches: MatchInfo[];
}

interface WeekManagerProps {
  leagueId: string;
}

export const WeekManager = ({ leagueId }: WeekManagerProps) => {
  const [weekGroups, setWeekGroups] = useState<WeekGroup[]>([]);
  const [isLoading, setIsLoading] = useState(false);

  // Dialog state
  const [assignDialogWeek, setAssignDialogWeek] = useState<number | null>(null);
  const [autoGenerateOpen, setAutoGenerateOpen] = useState(false);

  const fetchData = useCallback(async () => {
    if (!leagueId) return;
    setIsLoading(true);

    try {
      // Fetch all league_matches with joined cricket_match data
      const { data: matchesData, error: matchesError } = await supabase
        .from('league_matches')
        .select(`
          match_id,
          week,
          stats_imported,
          cricket_matches!inner (
            match_description,
            match_date,
            state,
            team1_name,
            team2_name
          )
        `)
        .eq('league_id', leagueId)
        .order('week');

      if (matchesError) throw matchesError;

      // Transform into MatchInfo array
      const allMatches: MatchInfo[] = (matchesData || []).map((row) => {
        const cm = row.cricket_matches;
        return {
          match_id: row.match_id,
          week: row.week,
          stats_imported: row.stats_imported || false,
          match_title:
            cm.match_description ||
            `${cm.team1_name || 'TBC'} vs ${cm.team2_name || 'TBC'}`,
          match_date: cm.match_date || '',
          state: cm.state || 'Upcoming',
        };
      });

      // Group by week
      const weekMap = new Map<number | null, MatchInfo[]>();
      for (const match of allMatches) {
        const key = match.week;
        if (!weekMap.has(key)) weekMap.set(key, []);
        weekMap.get(key)!.push(match);
      }

      // Sort matches within each group by date
      for (const matches of weekMap.values()) {
        matches.sort((a, b) => new Date(a.match_date).getTime() - new Date(b.match_date).getTime());
      }

      // Build week groups: numbered weeks first, then unassigned
      const weekNumbers = [...weekMap.keys()].filter((w): w is number => w !== null).sort((a, b) => a - b);
      const groups: WeekGroup[] = [];

      for (const week of weekNumbers) {
        groups.push({
          week,
          matches: weekMap.get(week) || [],
        });
      }

      // Add unassigned group if there are unassigned matches
      const unassigned = weekMap.get(null);
      if (unassigned && unassigned.length > 0) {
        groups.push({
          week: null,
          matches: unassigned,
        });
      }

      setWeekGroups(groups);
    } catch (error) {
      console.error('Error fetching week data:', error);
      toast.error('Failed to load week data');
    } finally {
      setIsLoading(false);
    }
  }, [leagueId]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  const handleAddNewWeek = async () => {
    // Find the next week number
    const existingWeeks = weekGroups
      .map((g) => g.week)
      .filter((w): w is number => w !== null);
    const nextWeek = existingWeeks.length > 0 ? Math.max(...existingWeeks) + 1 : 1;

    // Open the assign dialog directly for the new week number
    setAssignDialogWeek(nextWeek);
  };

  // Collect unassigned matches for the assign dialog
  const unassignedMatches = weekGroups
    .find((g) => g.week === null)
    ?.matches.map((m) => ({
      match_id: m.match_id,
      match_title: m.match_title,
      match_date: m.match_date,
    })) || [];

  const hasUnassigned = unassignedMatches.length > 0;

  return (
    <div className="space-y-4">
      {/* Action Bar */}
      <div className="flex items-center gap-2">
        {hasUnassigned && (
          <Button
            variant="outline"
            size="sm"
            className="h-8 text-xs"
            onClick={() => setAutoGenerateOpen(true)}
          >
            <Wand2 className="w-3 h-3 mr-1" />
            Auto-Generate Weeks
          </Button>
        )}
        <Button
          variant="outline"
          size="sm"
          className="h-8 text-xs"
          onClick={handleAddNewWeek}
          disabled={!hasUnassigned}
        >
          <Plus className="w-3 h-3 mr-1" />
          New Week
        </Button>
      </div>

      {/* Week Cards */}
      {isLoading ? (
        <div className="flex items-center justify-center py-8">
          <Loader2 className="w-6 h-6 animate-spin text-muted-foreground" />
        </div>
      ) : weekGroups.length === 0 ? (
        <p className="text-sm text-muted-foreground text-center py-4">
          No matches found for this league.
        </p>
      ) : (
        <div className="space-y-2">
          {weekGroups.map((group) => (
            <WeekCard
              key={group.week ?? 'unassigned'}
              leagueId={leagueId}
              week={group.week}
              matches={group.matches}
              onMatchRemoved={fetchData}
              onAddMatchesClick={(week) => setAssignDialogWeek(week)}
            />
          ))}
        </div>
      )}

      {/* Assign Matches Dialog */}
      {assignDialogWeek !== null && (
        <MatchAssignDialog
          open={true}
          onOpenChange={(open) => {
            if (!open) setAssignDialogWeek(null);
          }}
          leagueId={leagueId}
          targetWeek={assignDialogWeek}
          unassignedMatches={unassignedMatches}
          onAssigned={fetchData}
        />
      )}

      {/* Auto-Generate Dialog */}
      <AutoGenerateDialog
        open={autoGenerateOpen}
        onOpenChange={setAutoGenerateOpen}
        leagueId={leagueId}
        onApplied={fetchData}
      />

    </div>
  );
};
